module Jobs
  class UpdateStocks < Jobs::Scheduled

  include Sidekiq::Worker

    require "net/http"
    require "uri"

    every 5.minutes
    
    def execute(args)
      
        # find all stocks in tekindex
          
        @tickers = []

        # find all favorited stocks
        puts "Finding all favorite stocks"

        User.find_each do |user|
      
          puts "finding favorites for user id: #{user.id}"
          
          unless user.custom_fields["favorite_stocks"].nil? || user.custom_fields["favorite_stocks"].empty?
            
            users_favorite_stocks = user.custom_fields["favorite_stocks"].split(',')
            # puts users_favorite_stocks

            # add to array
            @tickers.concat users_favorite_stocks

          end
        end

        # find all stocks ever used in trades (ever in a portfolio) as well

        sql =  "-- [params]
                -- string :user_id = 1
                -- string :symbol = funcom-ol

                WITH raw AS (
                    SELECT psr.key as key, CAST(psr.value as JSON) as value
                    FROM plugin_store_rows psr
                    WHERE plugin_name = 'tekportfolio'
                ),
                data AS(
                    SELECT  
                        value->>'user_id' as user_id,
                        value->>'symbol' as symbol,
                        value->>'timestamp' as timestamp,
                        value->>'num_stocks' as num_stocks,
                        value->>'unit_price' as unit_price,
                        value->>'comment' as comment
                    FROM raw
                )

                SELECT distinct lower(symbol)
                FROM data
                where symbol is not null"

        trade_symbols = ActiveRecord::Base.connection.execute(sql)
  
        puts "found stocks ever used in trades/portfolio: "
        puts trade_symbols.values
        
        @list_of_strings = []
        trade_symbols.values.each do |trade_symbol|
           @list_of_strings.push(trade_symbol[0]) # adds string in array to list, silly workaround
#          puts trade_symbol[0]
        end
 #       puts @list_of_strings
      
        unless @list_of_strings.nil?
          # add to array
            @tickers.concat @list_of_strings
        end

         ose_tickers = 
          ['ASC.OL',
          'AFG.OL',
          'AKVA.OL',
          'ADEA.OL',
          'ADEB.OL',
          'AKA.OL',
          'AKER.OL',
          'AKERBP.OL',
          'AKSO.OL',
          'AMSC.OL',
          'APP.OL',
          'AQUA.OL',
          'ARCHER.OL',
          'ARCUS.OL',
          'AFK.OL',
          'ASETEK.OL',
          'ATEA.OL',
          'ATLA-NOK.OL',
          'AURG.OL',
          'AUSS.OL',
          'AVANCE.OL',
          'AVM.OL',
          'AWDR.OL',
          'AXA.OL',
          'B2H.OL',
          'BWLPG.OL',
          'BWO.OL',
          'BAKKA.OL',
          'BEL.OL',
          'BGBIO.OL',
          'BIOTEC.OL',
          'BON.OL',
          'BOR.OL',
          'BDRILL.OL',
          'BRG.OL',
          'BOUVET.OL',
          'BMA.OL',
          'COV.OL',
          'CRAYON.OL',
          'CXENSE.OL',
          'DNB.OL',
          'OBXEDNB.OL',
          'DNO.OL',
          'DOF.OL',
          'DAT.OL',
          'DDASA.OL',
          'EMAS.OL',
          'EVRY.OL',
          'EIOF.OL',
          'EMGS.OL',
          'ELE.OL',
          'ELK.OL',
          'ENDUR.OL',
          'ENTRA.OL',
          'EQNR.OL',
          'EPR.OL',
          'FLNG.OL',
          'FJORD.OL',
          'FKRAFT.OL',
          'FRO.OL',
          'FUNCOM.OL',
          'RISH.OL',
          'GIG.OL',
          'GJF.OL',
          'GOGL.OL',
          'GOD.OL',
          'GSF.OL',
          'GYL.OL',
          'HAVI.OL',
          'HYARD.OL',
          'HELG.OL',
          'HEX.OL',
          'HIDDN.OL',
          'HLNG.OL',
          'HSPG.OL',
          'IDEX.OL',
          'INC.OL',
          'INFRNT.OL',
          'INSR.OL',
          'IOX.OL',
          'ITE.OL',
          'JIN.OL',
          'JAEREN.OL',
          'KID.OL',
          'KIT.OL',
          'KOMP.OL',
          'KOA.OL',
          'KOG.OL',
          'KVAER.OL',
          'LSG.OL',
          'MPCC.OL',
          'MGN.OL',
          'MSEIS.OL',
          'MEDI.OL',
          'MELG.OL',
          'MOWI.OL',
          'MULTI.OL',
          'NEL.OL',
          'NEXT.OL',
          'NRC.OL',
          'NTS.OL',
          'NAPA.OL',
          'NAVA.OL',
          'NANO.OL',
          'NOD.OL',
          'NHY.OL',
          'NODL.OL',
          'NRS.OL',
          'NAS.OL',
          'NOR.OL',
          'NOFI.OL',
          'NPRO.OL',
          'OCY.OL',
          'OTS.OL',
          'ODL.OL',
          'ODF.OL',
          'ODFB.OL',
          'OLT.OL',
          'ORK.OL',
          'OTELLO.OL',
          'PCIB.OL',
          'PEN.OL',
          'PARB.OL',
          'PGS.OL',
          'PSE.OL',
          'PHO.OL',
          'PLCS.OL',
          'POL.OL',
          'PRS.OL',
          'PROTCT.OL',
          'QFR.OL',
          'QEC.OL',
          'RAKP.OL',
          'REC.OL',
          'REACH.OL',
          'SDSD.OL',
          'SAS-NOK.OL',
          'SALM.OL',
          'SALMON.OL',
          'SADG.OL',
          'SBANK.OL',
          'SSO.OL',
          'SCHA.OL',
          'SCHB.OL',
          'SBX.OL',
          'SDRL.OL',
          'SSG.OL',
          'SBO.OL',
          'SHLF.OL',
          'SIOFF.OL',
          'SKUE.OL',
          'SOGN.OL',
          'SOLON.OL',
          'SOFF.OL',
          'SBVG.OL',
          'NONG.OL',
          'SNOR.OL',
          'RING.OL',
          'MING.OL',
          'SRBANK.OL',
          'SOAG.OL',
          'SPOL.OL',
          'MORG.OL',
          'SOR.OL',
          'SBTE.OL',
          'SVEG.OL',
          'SPOG.OL',
          'SPU.OL',
          'SBLK.OL',
          'SNI.OL',
          'STB.OL',
          'STORM.OL',
          'STRONG.OL',
          'SUBC.OL',
          'TGS.OL',
          'TTS.OL',
          'TRVX.OL',
          'TEAM.OL',
          'TECH.OL',
          'TEL.OL',
          'SSC.OL',
          'THIN.OL',
          'TOM.OL',
          'TOTG.OL',
          'TRE.OL',
          'VEI.OL',
          'VISTIN.OL',
          'VVL.OL',
          'WALWIL.OL',
          'WSTEP.OL',
          'WWI.OL',
          'WWIB.OL',
          'WILS.OL',
          'OBXEXACT.OL',
          'OBXEXDBEAR.OL',
          'OBXEXDBULL.OL',
          'XXL.OL',
          'YAR.OL',
          'ZAL.OL',
          'PLT.OL']

        oax_tickers = [
        'FIVEPG.OL',
        'AEGA.OL',
        'APCL.OL',
        'ABT.OL',
        'ALNG.OL',
        'EAM.OL',
        'HBC.OL',
        'HUNT.OL',
        'NATTO.OL',
        'NOM.OL',
        'NORTH.OL',
        'OET.OL',
        'PHLY.OL',
        'PPG-PREF.OL',
        'ROM.OL',
        'SAGA.OL',
        'SSHIP.OL',
        'SBULK.OL']

        st_tickers = ['2CUREX.ST',
        'FIVEPGO.ST',
        'A1M.ST',
        'ATRE.ST',
        'AAK.ST',
        'FASTAT.ST',
        'ABB.ST',
        'ASCO.ST',
        'ADDV-A.ST',
        'ADDV-B.ST',
        'AFGO.ST',
        'AEC.ST',
        'AKVAO.ST',
        'ALLG-B.ST',
        'ALM.ST',
        'ALM-PREF.ST',
        'AQ.ST',
        'ASSA-B.ST',
        'ABSO.ST',
        'ACAD.ST',
        'ACAN-B.ST',
        'ACARIX.ST',
        'ACCON.ST',
        'ATIC.ST',
        'ACTI.ST',
        'ACM.ST',
        'ALIF-B.ST',
        'ADDERA.ST',
        'ANOD-B.ST',
        'ADDT-B.ST',
        'ADEAO.ST',
        'ADEBO.ST',
        'ADVE.ST',
        'AEGAO.ST',
        'AOI.ST',
        'APCLO.ST',
        'AGES-B.ST',
        'AGRO.ST',
        'AM1S.ST',
        'AINO.ST',
        'AKAO.ST',
        'AKEL-PREF.ST',
        'AKERO.ST',
        'AKERBPO.ST',
        'AKSOO.ST',
        'ALCA.ST',
        'ALELIO.ST',
        'ALFA.ST',
        'ALIG.ST',
        'ATORX.ST',
        'ALZCUR.ST',
        'ALZ.ST',
        'AMAST.ST',
        'AMAST-PREF.ST',
        'AMBEA.ST',
        'AMSCO.ST',
        'ANNX.ST',
        'ANOT.ST',
        'APPO.ST',
        'ABTO.ST',
        'AQUAO.ST',
        'AAP-B.ST',
        'ARCHERO.ST',
        'ARCOMA.ST',
        'ARCT.ST',
        'ARP.ST',
        'ARCUSO.ST',
        'AFKO.ST',
        'ARION-SDB.ST',
        'ARISE.ST',
        'ARJO-B.ST',
        'AROC.ST',
        'AROS-PREF.ST',
        'ASAI.ST',
        'ASAP.ST',
        'ACE.ST',
        'ASETEKO.ST',
        'ASPIRE.ST',
        'AZN.ST',
        'ATEAO.ST',
        'ATLA-NOKO.ST',
        'ATCO-A.ST',
        'ATCO-B.ST',
        'ATRLJ-B.ST',
        'ATT.ST',
        'ATVEXA-B.ST',
        'AUR.ST',
        'AUSSO.ST',
        'ALIV-SDB.ST',
        'AVANCEO.ST',
        'AZA.ST',
        'AVEN.ST',
        'AVMO.ST',
        'AVT-B.ST',
        'AWRD.ST',
        'AWDRO.ST',
        'ALNGO.ST',
        'AXAO.ST',
        'AXFO.ST',
        'AXOLOT.ST',
        'AYIMA-B.ST',
        'AZELIO.ST',
        'B2HO.ST',
        'B3.ST',
        'BONES.ST',
        'BEGR.ST',
        'BIM.ST',
        'BONEX.ST',
        'BTS-B.ST',
        'BWLPGO.ST',
        'BWOO.ST',
        'BACTI-B.ST',
        'BAKKAO.ST',
        'BALCO.ST',
        'NHCBHFFS.ST',
        'BUSER.ST',
        'BAYN.ST',
        'BEIA-B.ST',
        'BELE.ST',
        'BEIJ-B.ST',
        'BELO.ST',
        'BGBIOO.ST',
        'BERG-B.ST',
        'BRG-B.ST',
        'BESQ.ST',
        'BETS-B.ST',
        'BETCO.ST',
        'BILI-A.ST',
        'BILL.ST',
        'BINERO.ST',
        'BIOWKS.ST',
        'BIOA-B.ST',
        'BIOG-B.ST',
        'BINV.ST',
        'BIOS.ST',
        'BIOT.ST',
        'BIOTECO.ST',
        'BIOVIC-B.ST',
        'BORG.ST',
        'BOL.ST',
        'BONAV-A.ST',
        'BONAV-B.ST',
        'BONG.ST',
        'BONO.ST',
        'BONAS.ST',
        'BOOZT.ST',
        'BORO.ST',
        'BDRILLO.ST',
        'BRGO.ST',
        'BOTX.ST',
        'BOUL.ST',
        'BOUVETO.ST',
        'BRAV.ST',
        'BRE2.ST',
        'BRIG.ST',
        'BRIN-B.ST',
        'BUFAB.ST',
        'BULTEN.ST',
        'BURE.ST',
        'BYGGP.ST',
        'BHG.ST',
        'BMAO.ST',
        'BMAX.ST',
        'AJA-B.ST',
        'CRAD-B.ST',
        'CAG.ST',
        'CLNK-B.ST',
        'SINCH.ST',
        'CTT.ST',
        'CALTX.ST',
        'CAMX.ST',
        'CANTA.ST',
        'CAPAC.ST',
        'CAST.ST',
        'CAT-A.ST',
        'CAT-B.ST',
        'CATE.ST',
        'CTM.ST',
        'CCC.ST',
        'CI-B.ST',
        'CEVI.ST',
        'CHER-B.ST',
        'CBTT-B.ST',
        'CHRO.ST',
        'CIBUS.ST',
        'CIMCO.ST',
        'CLAS-B.ST',
        'CLAV.ST',
        'CLEMO.ST',
        'CLEM.ST',
        'CLIME-B.ST',
        'CLS-B.ST',
        'CLA-B.ST',
        'COLL.ST',
        'COMBI.ST',
        'COIC.ST',
        'CCOR-B.ST',
        'CONF.ST',
        'CONS-B.ST',
        'COVO.ST',
        'COOR.ST',
        'COPP-B.ST',
        'CORE-PREF.ST',
        'CORE-A.ST',
        'CORE-B.ST',
        'CLBIO.ST',
        'CE.ST',
        'CRAYONO.ST',
        'CRED-A.ST',
        'CFISH.ST',
        'CUR.ST',
        'CXENSEO.ST',
        'CYB1.ST',
        'CYXO.ST',
        'DDM.ST',
        'DNBO.ST',
        'DNOO.ST',
        'DOFO.ST',
        'DORO.ST',
        'DATO.ST',
        'DEDI.ST',
        'DEFL-B.ST',
        'DELARK.ST',
        'DEVP-B.ST',
        'DIAH.ST',
        'DMYD-B.ST',
        'DIGN.ST',
        'DIST.ST',
        'DIOS.ST',
        'DNBNOR-OBXO.ST',
        'DDASAO.ST',
        'DOME.ST',
        'DOM.ST',
        'DOXA.ST',
        'DRIL.ST',
        'DUNI.ST',
        'DURC-B.ST',
        'DUST.ST',
        'EAMO.ST',
        'EMASO.ST',
        'NLAB.ST',
        'EVRYO.ST',
        'EAST.ST',
        'EDGE.ST',
        'EFFP.ST',
        'EIOFO.ST',
        'ELAN-B.ST',
        'ELEC.ST',
        'ELUX-A.ST',
        'ELUX-B.ST',
        'EMGSO.ST',
        'EKTA-B.ST',
        'ELEO.ST',
        'ELKO.ST',
        'ELN.ST',
        'ELOS-B.ST',
        'ELTEL.ST',
        'EMPIR-B.ST',
        'ENQ.ST',
        'ENDO.ST',
        'ENDURO.ST',
        'ENEA.ST',
        'EOS.ST',
        'ENERS.ST',
        'ENRO.ST',
        'ENRO-PREF.ST',
        'ERMA.ST',
        'ENTRAO.ST',
        'ENZY.ST',
        'EOLU-B.ST',
        'EPI-A.ST',
        'EPI-B.ST',
        'EPIS-B.ST',
        'EQNRO.ST',
        'ERIC-A.ST',
        'ERIC-B.ST',
        'ESSITY-A.ST',
        'ESSITY-B.ST',
        'ETX.ST',
        'EPRO.ST',
        'EVO.ST',
        'EXPRS2.ST',
        'FLNGO.ST',
        'FMM-B.ST',
        'FRISQ.ST',
        'FABG.ST',
        'FAG.ST',
        'FPAR.ST',
        'FPAR-PREF.ST',
        'BALD-B.ST',
        'TRIAN-B.ST',
        'FEEL.ST',
        'FOI-B.ST',
        'FERRO.ST',
        'FNM.ST',
        'FIL.ST',
        'FING-B.ST',
        'FIRE.ST',
        'FJORDO.ST',
        'FKRAFTO.ST',
        'FLEXQ.ST',
        'FLEXM.ST',
        'FLUI.ST',
        'FOOT-PREF.ST',
        'FOOT-B.ST',
        'FPIP.ST',
        'FRAM-B.ST',
        'FRILL-B.ST',
        'FROO.ST',
        'FUNCOMO.ST',
        'G5EN.ST',
        'RISHO.ST',
        'GHP.ST',
        'GWS.ST',
        'GABA.ST',
        'GCOR.ST',
        'GIGO.ST',
        'GIGSEK.ST',
        'GAPW-B.ST',
        'GARO.ST',
        'GPX.ST',
        'GENI.ST',
        'GPG-PREF.ST',
        'GENO.ST',
        'GETI-B.ST',
        'GJFO.ST',
        'GLOBAL.ST',
        'GOGLO.ST',
        'GOMX.ST',
        'GODO.ST',
        'GREAT.ST',
        'GREEN.ST',
        'GSFO.ST',
        'GRNG.ST',
        'GUNN.ST',
        'GYLO.ST',
        'GHUS-B.ST',
        'HDW-B.ST',
        'HPOL-B.ST',
        'HMS.ST',
        'HLDX.ST',
        'HANDI.ST',
        'HNSA.ST',
        'HANZA.ST',
        'HAVIO.ST',
        'HAV-B.ST',
        'HYARDO.ST',
        'HEBA-B.ST',
        'HEGR.ST',
        'HEIM-PREF.ST',
        'HELIO.ST',
        'HEM-B.ST',
        'HEMC.ST',
        'HEMF.ST',
        'HEMF-PREF.ST',
        'HM-B.ST',
        'HEXA-B.ST',
        'HEXO.ST',
        'HTRO.ST',
        'HIQ.ST',
        'HIDDNO.ST',
        'HIFA-B.ST',
        'HBCO.ST',
        'HOFI.ST',
        'HOLM-A.ST',
        'HOLM-B.ST',
        'HOYLU.ST',
        'HUFV-A.ST',
        'HUFV-C.ST',
        'HUM.ST',
        'HUNTO.ST',
        'HUSQ-A.ST',
        'HUSQ-B.ST',
        'HLNGO.ST',
        'HOVD.ST',
        'ITECH.ST',
        'IAR-B.ST',
        'ICA.ST',
        'ICTA.ST',
        'IDEXO.ST',
        'IRLAB-A.ST',
        'IRRAS.ST',
        'ISR.ST',
        'ITAB-B.ST',
        'IVISYS.ST',
        'ICO.ST',
        'IS.ST',
        'IMMU.ST',
        'IMMNOV.ST',
        'IMPC.ST',
        'INCOAX.ST',
        'INDEX.ST',
        'INCO.ST',
        'INDU-A.ST',
        'INDU-C.ST',
        'INDT.ST',
        'IBT-B.ST',
        'INFREA.ST',
        'INFRNTO.ST',
        'INISS-B.ST',
        'INSRO.ST',
        'INSTAL.ST',
        'INTEG-B.ST',
        'IOXO.ST',
        'IPCO.ST',
        'ENG.ST',
        'IVACC.ST',
        'INTRUM.ST',
        'INTU.ST',
        'INVE-A.ST',
        'INVE-B.ST',
        'IVSO.ST',
        'INWI.ST',
        'IRIS.ST',
        'ISOFOL.ST',
        'ITAL-SDB.ST',
        'ITEO.ST',
        'JLT.ST',
        'JM.ST',
        'JAYS.ST',
        'JETPAK.ST',
        'JINO.ST',
        'JDT.ST',
        'K2A-PREF.ST',
        'KABE-B.ST',
        'KAKEL.ST',
        'KAPIAB.ST',
        'KAMBI.ST',
        'KAN.ST',
        'KAHL.ST',
        'KARE.ST',
        'KAR.ST',
        'KARO.ST',
        'KDEV.ST',
        'KENH.ST',
        'KIDO.ST',
        'KIND-SDB.ST',
        'KINV-A.ST',
        'KINV-B.ST',
        'KITO.ST',
        'KLAR.ST',
        'KLOV-A.ST',
        'KLOV-B.ST',
        'KLOV-PREF.ST',
        'KNOW.ST',
        'KOMPO.ST',
        'KOAO.ST',
        'KOGO.ST',
        'KONT.ST',
        'KOPY.ST',
        'KLED.ST',
        'KVAERO.ST',
        'LIDDS.ST',
        'LAGR-B.ST',
        'LAMM-B.ST',
        'LATO-B.ST',
        'LAUR.ST',
        'LEMSE.ST',
        'LEO.ST',
        'LSGO.ST',
        'LIFCO-B.ST',
        'LLSW-B.ST',
        'LIME.ST',
        'LIAB.ST',
        'LINKAB.ST',
        'LIVI.ST',
        'LOG.ST',
        'LOOM-B.ST',
        'LOUDS.ST',
        'LUC.ST',
        'LUND-B.ST',
        'LUG.ST',
        'LUMI.ST',
        'LUPE.ST',
        'LYKO-A.ST',
        'LYXGREENBOND.ST',
        'MAGI.ST',
        'MPCCO.ST',
        'MQ.ST',
        'MACK-B.ST',
        'MAG.ST',
        'MGNO.ST',
        'MSEISO.ST',
        'MAHA-A.ST',
        'MEAB-B.ST',
        'MANG.ST',
        'MANTEX.ST',
        'MATRA.ST',
        'MAV.ST',
        'MAXF.ST',
        'MCAP.ST',
        'MEDR-B.ST',
        'MCOV-B.ST',
        'MEDIO.ST',
        'MVIR-B.ST',
        'MEKO.ST',
        'MSAB-B.ST',
        'MSON-A.ST',
        'MSON-B.ST',
        'MIDS.ST',
        'MIDW-A.ST',
        'MIDW-B.ST',
        'TIGO-SDB.ST',
        'MINEST.ST',
        'MIPS.ST',
        'MISE.ST',
        'MOB.ST',
        'ME.ST',
        'MTG-A.ST',
        'MTG-B.ST',
        'MOMENT.ST',
        'MMGR-B.ST',
        'MOWIO.ST',
        'MOXI.ST',
        'MULQ.ST',
        'MULTIO.ST',
        'MTRS.ST',
        'MYCR.ST',
        'NAXS.ST',
        'NCAB.ST',
        'NCC-A.ST',
        'NCC-B.ST',
        'NELO.ST',
        'NEXTO.ST',
        'NGQ.ST',
        'NGS.ST',
        'NIBE-B.ST',
        'NOTE.ST',
        'NTEK-B.ST',
        'NP3.ST',
        'NP3-PREF.ST',
        'NRCO.ST',
        'NTSO.ST',
        'NAPAO.ST',
        'NATTOO.ST',
        'NAVAO.ST',
        'NMAN.ST',
        'NEPA.ST',
        'NETG.ST',
        'NETI-B.ST',
        'NET-B.ST',
        'NJOB.ST',
        'NETM-B.ST',
        'NVP.ST',
        'NNH.ST',
        'NEWA-B.ST',
        'NEXAM.ST',
        'NXTMS.ST',
        'NICO.ST',
        'NILS.ST',
        'NIL-B.ST',
        'NITRO.ST',
        'NOBI.ST',
        'NOBINA.ST',
        'NOKIA-SEK.ST',
        'NOLA-B.ST',
        'NDA-SE.ST',
        'XGOSBEZI.ST',
        'XGOSBEZR.ST',
        'NENT-A.ST',
        'NENT-B.ST',
        'NFGAB.ST',
        'NIO.ST',
        'NOMO.ST',
        'NANOO.ST',
        'NODO.ST',
        'NWG.ST',
        'NHYO.ST',
        'NORTHO.ST',
        'NODLO.ST',
        'NRSO.ST',
        'NASO.ST',
        'NORO.ST',
        'NOFIO.ST',
        'NPROO.ST',
        'NUE.ST',
        'NYF.ST',
        'OEM-B.ST',
        'OASM.ST',
        'OBOYA-B.ST',
        'OCYO.ST',
        'OTSO.ST',
        'ODD.ST',
        'ODLO.ST',
        'ODFO.ST',
        'ODFBO.ST',
        'OETO.ST',
        'OLTO.ST',
        'OV.ST',
        'ONCO.ST',
        'OBAB.ST',
        'OPUS.ST',
        'ORX.ST',
        'ORGC.ST',
        'ORI.ST',
        'ORKO.ST',
        'ORTI-A.ST',
        'ORTI-B.ST',
        'OP.ST',
        'OP-PREF.ST',
        'OP-PREFB.ST',
        'OTELLOO.ST',
        'OVZON.ST',
        'PCIBO.ST',
        'PALS-B.ST',
        'PNDX-B.ST',
        'PENO.ST',
        'PAPI.ST',
        'PDX.ST',
        'PARBO.ST',
        'PAX.ST',
        'PEAB-B.ST',
        'PEGRO-PREF.ST',
        'PGSO.ST',
        'PSEO.ST',
        'PFE.ST',
        'PHLOG-B.ST',
        'PHLYO.ST',
        'PCAT.ST',
        'PHOO.ST',
        'PIEZO.ST',
        'PPG-PREFO.ST',
        'PLAZ-B.ST',
        'PLED.ST',
        'PLCSO.ST',
        'POLO.ST',
        'POLYG.ST',
        'POLY.ST',
        'POOL-B.ST',
        'PCELL.ST',
        'PRCO-B.ST',
        'PREC.ST',
        'PCOM-B.ST',
        'PREV-B.ST',
        'PRIC-B.ST',
        'PRIME.ST',
        'PRIME-PREF-B.ST',
        'PACT.ST',
        'PROB.ST',
        'PROF-B.ST',
        'PENG-B.ST',
        'PROMO.ST',
        'PRSO.ST',
        'PROTCTO.ST',
        'QFRO.ST',
        'QLINEA.ST',
        'QLRO.ST',
        'QUART.ST',
        'QUART-PREF.ST',
        'QECO.ST',
        'RAKPO.ST',
        'RECO.ST',
        'RLS.ST',
        'RNBS.ST',
        'RAIL.ST',
        'RAKE.ST',
        'RPLAN.ST',
        'RATO-A.ST',
        'RATO-B.ST',
        'RAY-B.ST',
        'REACHO.ST',
        'REALFI.ST',
        'RECI-B.ST',
        'REDS.ST',
        'REJL-B.ST',
        'RESURS.ST',
        'ROMO.ST',
        'RROS.ST',
        'SDSDO.ST',
        'S2M.ST',
        'SAAB-B.ST',
        'SAS.ST',
        'SECI.ST',
        'SECT-B.ST',
        'SJR-B.ST',
        'SKF-A.ST',
        'SKF-B.ST',
        'SSAB-A.ST',
        'SSAB-B.ST',
        'SSM.ST',
        'SWEC-A.ST',
        'SWEC-B.ST',
        'SAGAO.ST',
        'SAGA-A.ST',
        'SAGA-B.ST',
        'SAGA-D.ST',
        'SAGA-PREF.ST',
        'SALMO.ST',
        'SALMONO.ST',
        'SALT-B.ST',
        'SAPIAB.ST',
        'SBB-B.ST',
        'SBB-D.ST',
        'SBB-PREF.ST',
        'SAND.ST',
        'SANION.ST',
        'SAVOS.ST',
        'SAXG.ST',
        'SBANKO.ST',
        'SBOK.ST',
        'SCST.ST',
        'SDOS.ST',
        'SHOT.ST',
        'CMOTEC-B.ST',
        'SES.ST',
        'SSHIPO.ST',
        'SSOO.ST',
        'SCHAO.ST',
        'SCHBO.ST',
        'SCIB.ST',
        'SCOUT.ST',
        'SDIP-PREF.ST',
        'SDIP-B.ST',
        'STW.ST',
        'SBXO.ST',
        'SDRLO.ST',
        'SDS.ST',
        'SECU-B.ST',
        'SEDANA.ST',
        'SSGO.ST',
        'SBOO.ST',
        'SMF.ST',
        'SEMC.ST',
        'SENS.ST',
        'SENZA.ST',
        'SEZI.ST',
        'SRNKE-B.ST',
        'SERT.ST',
        'SNM.ST',
        'SHLFO.ST',
        'SIOFFO.ST',
        'SIMRIS-B.ST',
        'SINT.ST',
        'SIVE.ST',
        'SEB-A.ST',
        'SEB-C.ST',
        'SKA-B.ST',
        'SKIS-B.ST',
        'SKMO.ST',
        'SEAB-B.ST',
        'SEYE.ST',
        'SOF-B.ST',
        'SOLT.ST',
        'SOLNA.ST',
        'SOLONO.ST',
        'SOFFO.ST',
        'SONE.ST',
        'SBULKO.ST',
        'SRBANKO.ST',
        'SPEC.ST',
        'SPUO.ST',
        'SPIFF.ST',
        'SPOR.ST',
        'SPRINT.ST',
        'SBLKO.ST',
        'STAR-A.ST',
        'STAR-B.ST',
        'STEF-B.ST',
        'STIL.ST',
        'SF.ST',
        'STWK.ST',
        'SNIO.ST',
        'STE-A.ST',
        'STE-R.ST',
        'STBO.ST',
        'STORMO.ST',
        'STORY-B.ST',
        'STRAX.ST',
        'STRONGO.ST',
        'SVIK.ST',
        'SUBCO.ST',
        'SUS.ST',
        'SVED-B.ST',
        'AERO.ST',
        'SCA-A.ST',
        'SCA-B.ST',
        'SHB-A.ST',
        'SHB-B.ST',
        'SVOL-A.ST',
        'SVOL-B.ST',
        'SWED-A.ST',
        'SECARE.ST',
        'SWMA.ST',
        'SOBI.ST',
        'SWOL-B.ST',
        'SYSR.ST',
        'TCT.ST',
        'TCC.ST',
        'TFBANK.ST',
        'TGSO.ST',
        'THQN-B.ST',
        'TTSO.ST',
        'TAGM-B.ST',
        'TALK.ST',
        'TANGI.ST',
        'TEONE.ST',
        'TRVXO.ST',
        'TEAMO.ST',
        'TECHO.ST',
        'TEL2-A.ST',
        'TEL2-B.ST',
        'TELO.ST',
        'TELIA.ST',
        'TSEC.ST',
        'TEQ.ST',
        'TERRNT-B.ST',
        'TETY.ST',
        'LEX.ST',
        'SSCO.ST',
        'THINO.ST',
        'THULE.ST',
        'TIETOS.ST',
        'TOAD.ST',
        'TOBII.ST',
        'TOBIN.ST',
        'TOBIN-PREF.ST',
        'TOMO.ST',
        'TORSAB.ST',
        'TRAC-B.ST',
        'TRAD.ST',
        'TRANS.ST',
        '3KR.ST',
        'TREO.ST',
        'TREL-B.ST',
        'TRENT.ST',
        'TRIBO-B.ST',
        'TROAX.ST',
        'UNIBAP.ST',
        'UTG.ST',
        'UPSALE.ST',
        'URBIT.ST',
        'VBG-B.ST',
        'VEIO.ST',
        'VRG-B.ST',
        'VNE-SDB.ST',
        'VERI.ST',
        'VICO.ST',
        'VICP-PREF.ST',
        'VICP-A.ST',
        'VICP-B.ST',
        'VSSAB-B.ST',
        'VISTINO.ST',
        'VIT-B.ST',
        'VITR.ST',
        'VOLO.ST',
        'VOLO-PREF.ST',
        'VOLV-A.ST',
        'VOLV-B.ST',
        'VVLO.ST',
        'VEMF-SDB.ST',
        'VNV-SDB.ST',
        'WALWILO.ST',
        'WALL-B.ST',
        'WAYS.ST',
        'WESC.ST',
        'WSTEPO.ST',
        'WPAY.ST',
        'WIFOG.ST',
        'WIHL.ST',
        'WWIO.ST',
        'WWIBO.ST',
        'WILSO.ST',
        'WISE.ST',
        'XACT-BEAR.ST',
        'XACT-BEAR-2.ST',
        'XACT-BULL.ST',
        'XACT-BULL-2.ST',
        'XACTHDIV.ST',
        'XACT-NORDEN-30.ST',
        'OBXEXACTO.ST',
        'OBXEXDBEARO.ST',
        'OBXEXDBULLO.ST',
        'XACT-OMXS30.ST',
        'XACT-OBLIGATION.ST',
        'XACT-RAVAROR.ST',
        'XACT-SMABOLAG.ST',
        'XACT-SVERIGE.ST',
        'XANO-B.ST',
        'XMR.ST',
        'XXLO.ST',
        'XBRANE.ST',
        'XINT.ST',
        'XSPRAY.ST',
        'XDAX.ST',
        'XESC.ST',
        'XD3E.ST',
        'XX25.ST',
        'XAXJ.ST',
        'XMBR.ST',
        'XMEM.ST',
        'XXSC.ST',
        'XMEU.ST',
        'XMJP.ST',
        'XPXJ.ST',
        'XMRC.ST',
        'XMUS.ST',
        'XMWO.ST',
        'XDWD.ST',
        'XNIF.ST',
        'XDND.ST',
        'XRS2.ST',
        'XSPX.ST',
        'XS7R.ST',
        'XGSD.ST',
        'XVIVO.ST',
        'YARO.ST',
        'ZALO.ST',
        'ZAPLOX.ST',
        'ZETA.ST',
        'ZETA-PREF.ST',
        'ZZ-B.ST',
        'ZUTEC.ST',
        'AXIC-A.ST',
        'EWRK.ST',
        'MYFC.ST',
        'TASTE.ST',
        'PLTO.ST',
        'AAC.ST',
        'AF-B.ST',
        'ORES.ST']

        nyse_tickers = ['DDD',
        'MMM',
        'WBAI',
        'WUBA',
        'EGHT',
        'AHC',
        'ATEN',
        'AAC',
        'AIR',
        'ABB',
        'ABM',
        'ADT',
        'ACM',
        'AEG',
        'AJRD',
        'AES',
        'AFL',
        'MITT',
        'AGCO',
        'AKS',
        'ACV',
        'AME',
        'AMN',
        'AXR',
        'ARA',
        'ARR',
        'ASA',
        'ASGN',
        'T',
        'ATH',
        'AUO',
        'AVX',
        'AZZ',
        'ABBV',
        'ABT',
        'ANF',
        'JEQ',
        'AKR',
        'ACN',
        'ATV',
        'ATU',
        'AYI',
        'ADX',
        'AGRO',
        'ADNT',
        'AAP',
        'WMS',
        'ASX',
        'AER',
        'AMG',
        'AGR',
        'A',
        'AEM',
        'ADC',
        'AL',
        'APD',
        'ALG',
        'AGI',
        'ALK',
        'AIN',
        'ALB',
        'AA',
        'ALC',
        'ALEX',
        'ALX',
        'ARE',
        'BABA',
        'Y',
        'ATI',
        'ALLE',
        'AGN',
        'ALE',
        'AKP',
        'AC',
        'ADS',
        'AWF',
        'AB',
        'AFB',
        'NCZ',
        'AFC',
        'ALL',
        'AOD',
        'MO',
        'ACH',
        'AEE',
        'AMRC',
        'APU',
        'AMX',
        'AXL',
        'AEO',
        'AEP',
        'AXP',
        'AFG',
        'AMH',
        'AIG',
        'AWR',
        'AMT',
        'AVD',
        'AWK',
        'AMP',
        'ABC',
        'ANFI',
        'AP',
        'APH',
        'APC',
        'AU',
        'AXE',
        'NLY',
        'AM',
        'ANTM',
        'ANH',
        'AON',
        'APA',
        'AIV',
        'ARI',
        'AIT',
        'ATR',
        'APTV',
        'WTR',
        'MT',
        'ARCH',
        'ADM',
        'ARNC',
        'ARCO',
        'ASC',
        'ARD',
        'AGX',
        'ARGO',
        'ANET',
        'AI',
        'ARLO',
        'ARW',
        'AHT',
        'ASH',
        'AGO',
        'AZN',
        'AT',
        'ATO',
        'ACB',
        'AN',
        'AZO',
        'ATHM',
        'ALV',
        'AVB',
        'ACP',
        'AVY',
        'AVA',
        'AVP',
        'AX',
        'BBT',
        'BFR',
        'BBX',
        'BCE',
        'BHP',
        'BJ',
        'BGY',
        'BPT',
        'BP',
        'BRFS',
        'BRT',
        'BT',
        'BW',
        'MCI',
        'MPV',
        'BHGE',
        'BLL',
        'CIB',
        'BBVA',
        'BBD',
        'BLX',
        'BMA',
        'SAN',
        'BCH',
        'BXS',
        'BAC',
        'BOH',
        'BMO',
        'BK',
        'BNS',
        'BCS',
        'BKS',
        'B',
        'GOLD',
        'BAS',
        'BHC',
        'BAX',
        'BTE',
        'BZH',
        'BDX',
        'BMS',
        'BHE',
        'BRKA',
        'BRKB',
        'BBY',
        'BH',
        'BITA',
        'BKH',
        'BB',
        'BFZ',
        'BOE',
        'BKT',
        'BKN',
        'MUA',
        'MEN',
        'MUH',
        'MFL',
        'MUJ',
        'MHN',
        'MUE',
        'MUS',
        'MVT',
        'MYC',
        'MCA',
        'MYD',
        'MYF',
        'MFT',
        'MIY',
        'MYJ',
        'MYN',
        'MPA',
        'MQT',
        'MYI',
        'MQY',
        'BAF',
        'BBF',
        'BYM',
        'BFK',
        'BSE',
        'BCX',
        'BLK',
        'BHK',
        'DSU',
        'BGR',
        'MUC',
        'BBK',
        'BQH',
        'BNY',
        'BSD',
        'HRB',
        'BXG',
        'BA',
        'BCC',
        'BCEI',
        'BWA',
        'SAM',
        'BXP',
        'BSX',
        'BIF',
        'BOX',
        'BYD',
        'BRC',
        'BHR',
        'BDN',
        'LND',
        'BAK',
        'BGG',
        'BEDU',
        'EAT',
        'BCO',
        'BMY',
        'BRS',
        'BTI',
        'BR',
        'BAM',
        'BIP',
        'RA',
        'BEP',
        'BRO',
        'BC',
        'BPL',
        'BKI',
        'BKE',
        'BBW',
        'BG',
        'CAE',
        'CAI',
        'CBZ',
        'CBL',
        'IGR',
        'CBRE',
        'CBS',
        'CF',
        'GIB',
        'CMS',
        'CNA',
        'CNF',
        'CNO',
        'CNX',
        'CBH',
        'CAL',
        'CPL',
        'CRH',
        'CSS',
        'CTS',
        'CVI',
        'UAN',
        'CVS',
        'CBT',
        'COG',
        'CCC',
        'CRC',
        'CWT',
        'ELY',
        'CPE',
        'CBM',
        'CPT',
        'CCJ',
        'CPB',
        'CM',
        'CNI',
        'CNQ',
        'CP',
        'CAJ',
        'CGC',
        'CMD',
        'COF',
        'CSU',
        'CPRI',
        'CMO',
        'CRR',
        'CAH',
        'CSL',
        'KMX',
        'CCL',
        'CRS',
        'CSV',
        'CRI',
        'CVNA',
        'CAT',
        'FUN',
        'CDR',
        'CE',
        'CLS',
        'CEL',
        'CX',
        'CVE',
        'CEN',
        'CNP',
        'EBR',
        'EBR-B',
        'CPF',
        'CEE',
        'CTL',
        'CRL',
        'CHMI',
        'CHK',
        'CHKR',
        'CPK',
        'CVX',
        'CHS',
        'CIM',
        'DL',
        'CEA',
        'CHN',
        'CGA',
        'LFC',
        'CHL',
        'BORN',
        'SNP',
        'ZNH',
        'CHA',
        'CHU',
        'CYD',
        'CMG',
        'CHH',
        'CB',
        'CHD',
        'CIEN',
        'CI',
        'XEC',
        'CBB',
        'CIR',
        'C',
        'CIA',
        'CVEO',
        'CLH',
        'EMO',
        'CLF',
        'CLX',
        'CLDR',
        'CEO',
        'KOF',
        'KO',
        'CCEP',
        'CDE',
        'INB',
        'UTF',
        'RQI',
        'RFI',
        'CL',
        'CLNY',
        'CXP',
        'STK',
        'CCZ',
        'CMA',
        'FIX',
        'CMC',
        'CBU',
        'CYH',
        'CBD',
        'CIG',
        'ELP',
        'SID',
        'SBS',
        'CCU',
        'BVN',
        'CODI',
        'CRK',
        'CAG',
        'CXO',
        'CNDT',
        'COP',
        'ED',
        'STZ',
        'CSTM',
        'TCS',
        'CLR',
        'VLRS',
        'COO',
        'CTB',
        'CPA',
        'CLB',
        'CLGX',
        'COR',
        'GLW',
        'OFC',
        'CXW',
        'CZZ',
        'CMRE',
        'COT',
        'CUZ',
        'CVA',
        'CR',
        'BAP',
        'CS',
        'CPG',
        'CEQP',
        'CRT',
        'CCI',
        'CCK',
        'CRY',
        'CUB',
        'CFR',
        'CULP',
        'CW',
        'INSI',
        'DQ',
        'SITC',
        'DHT',
        'DNP',
        'DRD',
        'DTE',
        'DTF',
        'DXC',
        'DVA',
        'DHR',
        'DAC',
        'DRI',
        'DF',
        'DECK',
        'DE',
        'DDF',
        'DKL',
        'DK',
        'DELL',
        'DAL',
        'DLX',
        'DNR',
        'DB',
        'DXB',
        'KTF',
        'KSM',
        'DVN',
        'DEO',
        'DO',
        'DSSI',
        'DRH',
        'DSX',
        'DKS',
        'DBD',
        'DLR',
        'DDS',
        'DFS',
        'DIS',
        'DLB',
        'DG',
        'D',
        'DCP',
        'DPZ',
        'DCI',
        'LPG',
        'DSL',
        'DOV',
        'DVD',
        'DOW',
        'DWDP',
        'RDY',
        'DHF',
        'DSM',
        'LEO',
        'DRQ',
        'DS',
        'DCO',
        'DUC',
        'DUK',
        'DRE',
        'DY',
        'DLNG',
        'DX',
        'ECT',
        'EME',
        'E',
        'ENO',
        'EOG',
        'EPC',
        'EPR',
        'EQT',
        'ESE',
        'EXP',
        'EGP',
        'EMN',
        'KODK',
        'ETN',
        'EV',
        'EOS',
        'EFT',
        'EVN',
        'ETJ',
        'EVF',
        'EVG',
        'ECL',
        'EC',
        'EIX',
        'EW',
        'EE',
        'ESTC',
        'EGO',
        'EFC',
        'EARN',
        'AKOA',
        'AKOB',
        'ERJ',
        'EMES',
        'EBS',
        'EMR',
        'ECA',
        'NPO',
        'ENB',
        'EXK',
        'ENR',
        'ET',
        'ENIA',
        'EBF',
        'ESV',
        'ETM',
        'ETR',
        'EPD',
        'EVC',
        'ENZ',
        'EFX',
        'EQNR',
        'EQR',
        'EQS',
        'ESS',
        'ETH',
        'EURN',
        'EB',
        'RE',
        'EVRG',
        'EXC',
        'EXPR',
        'XOM',
        'FFG',
        'FDC',
        'FRC',
        'FMC',
        'FCN',
        'FN',
        'FDS',
        'FICO',
        'FDX',
        'AGM',
        'FRT',
        'FSS',
        'FII',
        'FMN',
        'RACE',
        'FGP',
        'FOE',
        'FCAU',
        'FIS',
        'FAF',
        'FBP',
        'FCF',
        'FHN',
        'FR',
        'AG',
        'FIF',
        'FE',
        'FIT',
        'FBC',
        'PFD',
        'PFO',
        'FFC',
        'FTK',
        'FLO',
        'FLS',
        'FLR',
        'FLY',
        'FMX',
        'FL',
        'F',
        'FSM',
        'FNV',
        'FI',
        'FC',
        'BEN',
        'FT',
        'FCX',
        'FMS',
        'FDP',
        'FRO',
        'FUL',
        'FF',
        'GBL',
        'GATX',
        'GNC',
        'GPX',
        'GES',
        'GCV',
        'GAB',
        'GGT',
        'GUT',
        'AJG',
        'GME',
        'GCI',
        'GDI',
        'GTX',
        'IT',
        'GLOG',
        'GNK',
        'GAM',
        'GD',
        'GE',
        'GIS',
        'GM',
        'GCO',
        'GWR',
        'GEL',
        'G',
        'GPC',
        'GNW',
        'GEO',
        'GGB',
        'GTY',
        'GIL',
        'GSK',
        'GNL',
        'GLP',
        'GPN',
        'GSL',
        'GOL',
        'GFI',
        'GS',
        'GER',
        'GRA',
        'GGG',
        'GWW',
        'GVA',
        'GPMT',
        'GPK',
        'GTN',
        'GHG',
        'GBX',
        'GEF',
        'GFF',
        'GPI',
        'PAC',
        'ASR',
        'RC',
        'TV',
        'GSH',
        'GWRE',
        'HCA',
        'HCC',
        'HCP',
        'HDB',
        'HNI',
        'HPQ',
        'HSBC',
        'HAE',
        'HK',
        'HAL',
        'HPF',
        'HBI',
        'HOG',
        'HMY',
        'HRS',
        'HSC',
        'HHS',
        'HIG',
        'HVT',
        'HE',
        'HR',
        'HL',
        'HEI',
        'HLX',
        'HP',
        'HLF',
        'HTGC',
        'HRTG',
        'HSY',
        'HTZ',
        'HES',
        'HPE',
        'HXL',
        'HCLP',
        'HPR',
        'ONE',
        'HIW',
        'HRC',
        'HI',
        'HLT',
        'HMLP',
        'HFC',
        'HD',
        'HMC',
        'HON',
        'HMN',
        'HRL',
        'HOS',
        'DHI',
        'HOV',
        'HNP',
        'HBM',
        'HUM',
        'HUN',
        'HY',
        'IAG',
        'IBN',
        'IEX',
        'IDT',
        'ING',
        'IVR',
        'IO',
        'IRS',
        'ITT',
        'IDA',
        'ITW',
        'IFN',
        'IBA',
        'IR',
        'INGR',
        'ITGR',
        'IHG',
        'INXN',
        'ICE',
        'IBM',
        'IFF',
        'IP',
        'INSW',
        'IPG',
        'IPI',
        'IVC',
        'VBF',
        'VCV',
        'VLT',
        'IVZ',
        'OIA',
        'VMO',
        'VKQ',
        'VPV',
        'IQI',
        'VVR',
        'VTN',
        'VGM',
        'IIM',
        'IRM',
        'ICL',
        'ITUB',
        'JPM',
        'JBL',
        'JEC',
        'JHX',
        'JOF',
        'JEF',
        'JKS',
        'JBT',
        'BTO',
        'JHS',
        'JHI',
        'HPI',
        'PDT',
        'JNJ',
        'JCI',
        'JLL',
        'JMEI',
        'JNPR',
        'JP',
        'JE',
        'KB',
        'KBH',
        'KBR',
        'KEM',
        'KKR',
        'KNOP',
        'KAI',
        'KSU',
        'KYN',
        'K',
        'KMT',
        'KW',
        'KDP',
        'KEG',
        'KEY',
        'KEYS',
        'KRC',
        'KMB',
        'KIM',
        'KMI',
        'KFS',
        'KGC',
        'KEX',
        'KSS',
        'PHG',
        'KOP',
        'KEP',
        'KF',
        'KFY',
        'KR',
        'LB',
        'LLL',
        'LCII',
        'LPL',
        'TLI',
        'LXU',
        'LTC',
        'LZB',
        'LH',
        'LCI',
        'LPI',
        'LVS',
        'EL',
        'LAZ',
        'LEA',
        'LEE',
        'BWG',
        'LM',
        'LEG',
        'LEJU',
        'LC',
        'LEN',
        'LII',
        'LXP',
        'USA',
        'ASG',
        'LLY',
        'LNC',
        'LNN',
        'LAD',
        'LAC',
        'LYV',
        'LTHM',
        'LYG',
        'LMT',
        'LPX',
        'LOW',
        'LUB',
        'LL',
        'LDL',
        'MTB',
        'MDC',
        'MHO',
        'MMS',
        'MBI',
        'MDU',
        'MFA',
        'MFCB',
        'MCR',
        'MGF',
        'CXE',
        'CMU',
        'CIF',
        'MIN',
        'CXH',
        'MMT',
        'MFM',
        'MFV',
        'MTG',
        'MGM',
        'MSA',
        'MSM',
        'MSCI',
        'MAC',
        'CLI',
        'M',
        'MMP',
        'MGA',
        'MX',
        'MGY',
        'MAIN',
        'MNK',
        'MANU',
        'MTW',
        'MAN',
        'MRO',
        'MPC',
        'MMI',
        'MCS',
        'HZO',
        'MKL',
        'VAC',
        'MMC',
        'MLM',
        'MTZ',
        'MAS',
        'MA',
        'MTDR',
        'MATX',
        'MXL',
        'MKC',
        'MDR',
        'MCD',
        'MUX',
        'MCK',
        'MTL',
        'MPW',
        'MED',
        'MCC',
        'MDT',
        'MRK',
        'MCY',
        'MDP',
        'MTH',
        'MTOR',
        'MTR',
        'MSB',
        'MET',
        'MTD',
        'MXE',
        'MXF',
        'MFGP',
        'MAA',
        'MLR',
        'MR',
        'MTX',
        'MFG',
        'MBT',
        'MOD',
        'MHK',
        'TAP',
        'MCO',
        'MS',
        'CAF',
        'MSD',
        'IIF',
        'MOS',
        'MSI',
        'MOV',
        'MLI',
        'MWA',
        'MUR',
        'MYE',
        'NC',
        'NCS',
        'NCR',
        'NKE',
        'NIO',
        'NL',
        'DNOW',
        'NRG',
        'NUS',
        'NBR',
        'NTP',
        'NFG',
        'NGG',
        'NHI',
        'NOV',
        'NPK',
        'NNN',
        'NRP',
        'NTZ',
        'NLS',
        'NCI',
        'NNA',
        'NM',
        'NMM',
        'NAV',
        'NNI',
        'HYB',
        'GF',
        'IRL',
        'NJR',
        'NEWM',
        'EDU',
        'NRZ',
        'SNR',
        'NYCB',
        'NYT',
        'NEU',
        'NEM',
        'NR',
        'NHF',
        'NEE',
        'NEP',
        'NI',
        'NE',
        'NBL',
        'NOK',
        'NMR',
        'OSB',
        'NAT',
        'NAO',
        'JWN',
        'NSC',
        'NOA',
        'NRT',
        'NOC',
        'NRE',
        'NWN',
        'NCLH',
        'NVS',
        'NVO',
        'NS',
        'NSS',
        'NUE',
        'NTR',
        'NAZ',
        'NAC',
        'NCA',
        'NXC',
        'NTC',
        'NEV',
        'NAD',
        'NMY',
        'NMT',
        'NUM',
        'NMI',
        'NUV',
        'NAN',
        'NNY',
        'NXN',
        'NNC',
        'NUO',
        'NQP',
        'JPC',
        'JPS',
        'JPT',
        'JPI',
        'NIM',
        'NXQ',
        'NXP',
        'NXR',
        'NSL',
        'NTX',
        'NPV',
        'OFG',
        'OGE',
        'OAK',
        'OAS',
        'OBE',
        'OXY',
        'OII',
        'OCN',
        'OIS',
        'ODC',
        'ORI',
        'OLN',
        'OHI',
        'OMC',
        'OMN',
        'ONDK',
        'OKE',
        'ORCL',
        'ORAN',
        'ORC',
        'ORN',
        'IX',
        'ORA',
        'OSK',
        'OR',
        'OSG',
        'OMI',
        'OC',
        'OI',
        'OXM',
        'TLK',
        'PCG',
        'GLT',
        'PD',
        'PTY',
        'PGP',
        'PFL',
        'RCS',
        'PJT',
        'PYX',
        'PNC',
        'PNM',
        'PKX',
        'PPG',
        'PPX',
        'PPL',
        'PSB',
        'PVH',
        'PACD',
        'PKG',
        'PANW',
        'PAM',
        'PKE',
        'PH',
        'PE',
        'PRTY',
        'BTU',
        'PSO',
        'JCP',
        'PEI',
        'PMT',
        'PAG',
        'PNR',
        'PBY',
        'PKI',
        'PBT',
        'PRGO',
        'PRSP',
        'PTR',
        'PBR',
        'PBRA',
        'PEO',
        'PFE',
        'PM',
        'PHI',
        'PSX',
        'PSXP',
        'PIR',
        'PCQ',
        'PCK',
        'PZC',
        'PHK',
        'PKO',
        'PMF',
        'PML',
        'PMX',
        'PNF',
        'PNI',
        'PYN',
        'PNW',
        'MAV',
        'PXD',
        'PBI',
        'PVTL',
        'PAA',
        'PLT',
        'PII',
        'POL',
        'PDS',
        'PIY',
        'PVG',
        'PRI',
        'PRA',
        'PG',
        'PGR',
        'PLD',
        'PRLB',
        'PFS',
        'PJH',
        'PRU',
        'PUK',
        'PEG',
        'PSA',
        'PHM',
        'PCF',
        'PMM',
        'PIM',
        'PMO',
        'PPT',
        'QTWO',
        'QEP',
        'KWR',
        'NX',
        'PWR',
        'DGX',
        'CTV',
        'REZI',
        'RLI',
        'RES',
        'RPM',
        'RRD',
        'RDN',
        'RL',
        'RPT',
        'RRC',
        'RJF',
        'RYAM',
        'RYN',
        'RTN',
        'O',
        'RHT',
        'RWT',
        'RF',
        'RGA',
        'RS',
        'RNR',
        'SOL',
        'RENN',
        'RSG',
        'RMD',
        'QSR',
        'RVI',
        'REV',
        'RIO',
        'RMG',
        'RBA',
        'RAD',
        'RHI',
        'ROK',
        'RCI',
        'ROG',
        'ROL',
        'ROP',
        'RST',
        'RY',
        'RBS',
        'RCL',
        'RDS-A',
        'RDS-B',
        'RVT',
        'RTEC',
        'R',
        'SAP',
        'EFL',
        'SAF',
        'CKH',
        'SJW',
        'SKM',
        'SLG',
        'SM',
        'STE',
        'STM',
        'SBR',
        'SB',
        'SFE',
        'CRM',
        'SBH',
        'SJT',
        'SDT',
        'SDR',
        'PER',
        'SD',
        'BSMX',
        'SAR',
        'SSL',
        'BFS',
        'SLB',
        'SCHW',
        'SWM',
        'SALT',
        'STNG',
        'SMG',
        'SA',
        'SDRL',
        'SDLP',
        'SEE',
        'SSW',
        'SCA',
        'SRE',
        'SXT',
        'SQNS',
        'SRG',
        'SCI',
        'SHAK',
        'SJR',
        'SHW',
        'SFL',
        'SHOP',
        'SBGL',
        'SBOW',
        'SPG',
        'SSD',
        'SHI',
        'SKX',
        'SNN',
        'AOS',
        'SJM',
        'SNAP',
        'SNA',
        'SQM',
        'SWI',
        'SAH',
        'SON',
        'SNE',
        'BID',
        'SOR',
        'SJI',
        'SO',
        'SCCO',
        'LUV',
        'SWX',
        'SWN',
        'SE',
        'TRK',
        'SAVE',
        'SRC',
        'SPOT',
        'S',
        'SQ',
        'JOE',
        'STAG',
        'SSI',
        'SMP',
        'SR',
        'SXI',
        'SWK',
        'STN',
        'SGU',
        'SCX',
        'SRT',
        'STT',
        'SCS',
        'SCM',
        'SCL',
        'STL',
        'STC',
        'SF',
        'EDF',
        'STON',
        'SRI',
        'STOR',
        'KTN',
        'KTH',
        'SYK',
        'RGR',
        'SPH',
        'SMFG',
        'SUI',
        'SLF',
        'SXCP',
        'SXC',
        'STI',
        'SU',
        'SUN',
        'SPN',
        'SUP',
        'SWZ',
        'SYF',
        'SNX',
        'SNV',
        'SYY',
        'SYX',
        'TAL',
        'TBC',
        'TCP',
        'TCF',
        'TEL',
        'TU',
        'TTI',
        'TSU',
        'TJX',
        'DATA',
        'TLRD',
        'TWN',
        'TSM',
        'SKT',
        'TPR',
        'TGT',
        'TTM',
        'TCO',
        'FTI',
        'TECK',
        'TK',
        'TGP',
        'TOO',
        'TNK',
        'TRC',
        'HQH',
        'HQL',
        'TDOC',
        'TEO',
        'TI',
        'TDY',
        'TFX',
        'VIV',
        'TEF',
        'TDI',
        'TDF',
        'EMF',
        'TEI',
        'GIM',
        'TPX',
        'TS',
        'TME',
        'THC',
        'TNC',
        'TEN',
        'TEX',
        'TX',
        'TEVA',
        'TPL',
        'TGH',
        'TXT',
        'BX',
        'CC',
        'SRV',
        'GPS',
        'HHC',
        'NWHM',
        'TMO',
        'TPRE',
        'TRI',
        'THO',
        'TDW',
        'TIF',
        'TKR',
        'TWI',
        'TOL',
        'TR',
        'TMK',
        'TTC',
        'TD',
        'NTG',
        'TOT',
        'TSS',
        'TM',
        'TRP',
        'TRU',
        'TCI',
        'TDG',
        'RIG',
        'TGS',
        'TRV',
        'TG',
        'TLRA',
        'TREX',
        'TY',
        'TRN',
        'TGI',
        'TBI',
        'TNP',
        'TUP',
        'TKC',
        'TRQ',
        'TPC',
        'TWLO',
        'TWTR',
        'TWO',
        'TYL',
        'TSN',
        'USB',
        'SLCA',
        'UBS',
        'UGI',
        'USNA',
        'USG',
        'UGP',
        'UAA',
        'UA',
        'UFI',
        'UNF',
        'UN',
        'UL',
        'UNP',
        'UIS',
        'UNT',
        'UMC',
        'UPS',
        'URI',
        'X',
        'UTX',
        'UNH',
        'UVV',
        'UHT',
        'UHS',
        'UNM',
        'UBP',
        'EGY',
        'VER',
        'VFC',
        'IGD',
        'PPR',
        'IRR',
        'MTN',
        'VALE',
        'VLO',
        'VHI',
        'VMI',
        'VAR',
        'VGR',
        'VEDL',
        'VEEV',
        'VTR',
        'VZ',
        'VSM',
        'VVI',
        'VNCE',
        'VIPS',
        'V',
        'VSH',
        'VSTO',
        'VSLR',
        'VMW',
        'VG',
        'VNO',
        'VMC',
        'WTI',
        'WPC',
        'WNS',
        'WPP',
        'WPX',
        'WNC',
        'WBC',
        'WAB',
        'WDR',
        'WAGE',
        'WMT',
        'WPG',
        'WRE',
        'WCN',
        'WM',
        'WAT',
        'WSO',
        'WTS',
        'WFT',
        'WBS',
        'WRI',
        'WMK',
        'WCG',
        'WFC',
        'WELL',
        'WCC',
        'WST',
        'WRK',
        'EMD',
        'EHI',
        'HIX',
        'HIO',
        'HYI',
        'PAI',
        'IGI',
        'MMU',
        'MHF',
        'MNP',
        'WES',
        'WU',
        'WBK',
        'WHG',
        'WY',
        'WPM',
        'WHR',
        'WTM',
        'WSR',
        'WLL',
        'WMB',
        'WSM',
        'WGO',
        'WIT',
        'WEC',
        'WWW',
        'INT',
        'WWE',
        'WOR',
        'XRX',
        'XIN',
        'XYL',
        'YETI',
        'YPF',
        'AUY',
        'YELP',
        'YRD',
        'YUMC',
        'YUM',
        'ZTO',
        'ZEN',
        'ZTS',
        'ZF',
        'ZTR',
        'NVT',
        'VJET']

        amex_tickers = ['GRU',
        'RJA',
        'RJI',
        'SBIO',
        'FAX',
        'IAF',
        'PALL',
        'PPLT',
        'ACU',
        'ATNM',
        'AE',
        'HDGE',
        'ACY',
        'AGE',
        'AXU',
        'AAU',
        'APT',
        'AMS',
        'USAS',
        'APHB',
        'AGT',
        'AKG',
        'AINC',
        'AUG',
        'AWX',
        'ASM',
        'BTG',
        'BCV',
        'BHB',
        'BRN',
        'BTX',
        'BDR',
        'CEI',
        'FYLD',
        'GVAL',
        'CANF',
        'ROX',
        'CVM',
        'CET',
        'CCF',
        'CQP',
        'LNG',
        'CVR',
        'CPHI',
        'GRI',
        'INXX',
        'CTO',
        'MCF',
        'CMT',
        'CRMD',
        'CLM',
        'CRF',
        'DHY',
        'DPW',
        'DXR',
        'VCF',
        'VMM',
        'VFL',
        'DNN',
        'DZZ',
        'DGZ',
        'DGP',
        'ASHR',
        'CN',
        'DRN',
        'TYD',
        'TMF',
        'TMV',
        'YANG',
        'ERY',
        'YINN',
        'DUST',
        'NUGT',
        'NAIL',
        'JDST',
        'JNUG',
        'LBJ',
        'INDL',
        'GASL',
        'RUSS',
        'RUSL',
        'SPXS',
        'SPXL',
        'LABD',
        'LABU',
        'SOXS',
        'SOXL',
        'CHAD',
        'CHAU',
        'EDZ',
        'EDC',
        'ERX',
        'FAZ',
        'FAS',
        'DRIP',
        'TZA',
        'TNA',
        'TECL',
        'DRV',
        'DMF',
        'UAG',
        'UCI',
        'FUD',
        'USV',
        'MJ',
        'SILJ',
        'SMHB',
        'EVM',
        'CEV',
        'EIM',
        'ENX',
        'EVY',
        'ECF',
        'MSN',
        'UUUU',
        'ENSV',
        'EGI',
        'ESP',
        'PFFL',
        'EMX',
        'FNI',
        'FDL',
        'FRI',
        'BDL',
        'FSI',
        'FSP',
        'FRD',
        'GGN',
        'JOB',
        'GMO',
        'CHIQ',
        'CHIE',
        'CHIX',
        'CHII',
        'CHIM',
        'COPX',
        'GXF',
        'GOEX',
        'LIT',
        'ARGT',
        'GXG',
        'GREK',
        'NGE',
        'NORW',
        'PGAL',
        'SIL',
        'SDIV',
        'URA',
        'GLO',
        'GORO',
        'AUMN',
        'GSS',
        'GV',
        'GTE',
        'GPL',
        'SIM',
        'EEB',
        'TAO',
        'FXA',
        'FXB',
        'FXC',
        'FXE',
        'FXS',
        'FRN',
        'XLG',
        'RPV',
        'RFV',
        'RZV',
        'HMG',
        'HEB',
        'CPI',
        'IMO',
        'IOR',
        'IHT',
        'FFTY',
        'LDRS',
        'IDN',
        'INS',
        'THM',
        'INUV',
        'VKI',
        'HAO',
        'FXF',
        'DBA',
        'UUP',
        'RPG',
        'CGW',
        'TAN',
        'PBW',
        'CVY',
        'ISR',
        'LGL',
        'LTS',
        'LBY',
        'CCA',
        'MAG',
        'CNY',
        'DRR',
        'SMH',
        'XLB',
        'MICR',
        'NTN',
        'NNVC',
        'NHC',
        'NAVB',
        'NBW',
        'NBH',
        'NBO',
        'GBR',
        'NGD',
        'NAK',
        'NOG',
        'NG',
        'OCX',
        'PTN',
        'PRK',
        'HYLD',
        'PLAG',
        'PLG',
        'PLM',
        'PW',
        'BAB',
        'PZD',
        'DBB',
        'DBC',
        'DTO',
        'DBE',
        'DBO',
        'DBS',
        'UDN',
        'PXJ',
        'PSJ',
        'PGF',
        'PXSV',
        'PBD',
        'PHB',
        'PIN',
        'PSP',
        'PZA',
        'SPLV',
        'PEX',
        'DOG',
        'SEF',
        'SJB',
        'EUM',
        'MYY',
        'PSQ',
        'RWM',
        'SH',
        'SBB',
        'SVXY',
        'VIXY',
        'UVXY',
        'UBT',
        'UST',
        'UYM',
        'UCO',
        'BOIL',
        'UCC',
        'DDM',
        'ULE',
        'XPP',
        'UYG',
        'UGL',
        'RXL',
        'UXI',
        'EET',
        'MVV',
        'DIG',
        'QLD',
        'URE',
        'UWM',
        'SSO',
        'USD',
        'AGQ',
        'ROM',
        'UPW',
        'YCL',
        'UDOW',
        'URTY',
        'UPRO',
        'SRTY',
        'SPXU',
        'SMN',
        'SCO',
        'KOLD',
        'SZK',
        'SCC',
        'DXD',
        'EUO',
        'EPV',
        'SKF',
        'GLL',
        'TBT',
        'PST',
        'EEV',
        'MZZ',
        'DUG',
        'QID',
        'SRS',
        'TWM',
        'SDS',
        'ZSL',
        'YCS',
        'FXP',
        'HACK',
        'IPAY',
        'SIZ',
        'RVP',
        'RNN',
        'ROBO',
        'SIF',
        'BIL',
        'MBG',
        'SJNK',
        'JNK',
        'BWX',
        'FEZ',
        'RWR',
        'DIA',
        'DGT',
        'GLD',
        'MDY',
        'HYMB',
        'SPY',
        'XAR',
        'GXC',
        'SDY',
        'GMF',
        'EWX',
        'WDIV',
        'XHS',
        'KIE',
        'GWX',
        'XME',
        'XES',
        'XOP',
        'XPH',
        'XSD',
        'XLY',
        'XLP',
        'XLE',
        'XLF',
        'XLV',
        'XLI',
        'XLK',
        'XLU',
        'XBI',
        'XHB',
        'PSK',
        'SAND',
        'SCHE',
        'SCHA',
        'SCHZ',
        'SEB',
        'SVT',
        'SILV',
        'SVM',
        'XPL',
        'SGB',
        'PHYS',
        'CEF',
        'SPPP',
        'PSLV',
        'SSY',
        'SYN',
        'TRX',
        'TGB',
        'TGC',
        'CORN',
        'SOYB',
        'WEAT',
        'ALO',
        'TMP',
        'TAT',
        'TRT',
        'LBDC',
        'BDCL',
        'CEFL',
        'DVHL',
        'MRRL',
        'LMLP',
        'MORL',
        'UQM',
        'UMDD',
        'SDOW',
        'USL',
        'UAMY',
        'BNO',
        'USCI',
        'UNG',
        'USO',
        'UUU',
        'URG',
        'UEC',
        'MOO',
        'PEK',
        'CNXT',
        'KOL',
        'EVX',
        'SCIF',
        'OIH',
        'RTH',
        'SLX',
        'FRAK',
        'AFK',
        'BRF',
        'GEX',
        'GDX',
        'IDX',
        'GDXJ',
        'REMX',
        'RSX',
        'NLR',
        'VNM',
        'VCR',
        'VDC',
        'VIG',
        'VDE',
        'EDV',
        'VXF',
        'VEU',
        'VSS',
        'VEA',
        'VWO',
        'VPL',
        'VGK',
        'VFH',
        'VUG',
        'VHT',
        'VYM',
        'VIS',
        'VGT',
        'VV',
        'VAW',
        'MGC',
        'VO',
        'VOT',
        'VOE',
        'VNQ',
        'VOO',
        'VB',
        'VBK',
        'VBR',
        'VOX',
        'VTI',
        'VT',
        'VPU',
        'VTV',
        'DWT',
        'UWT',
        'DGAZ',
        'UGAZ',
        'VGZ',
        'EAD',
        'WYY',
        'WTT',
        'USDU',
        'CYB',
        'DTN',
        'DGS',
        'DEM',
        'DLS',
        'DFJ',
        'EZM',
        'DES',
        'EMAN',
        'IBIO',
        'JJA',
        'JJU',
        'NIB',
        'JO',
        'JJC',
        'BAL',
        'JJG',
        'COW',
        'PGM',
        'SGG',
        'TLH',
        'DVYA',
        'FXI',
        'ICF',
        'IPAC',
        'IVV',
        'IJH',
        'IJR',
        'IYY',
        'EFAV',
        'EEMV',
        'EUMV',
        'ACWV',
        'USMV',
        'INTF',
        'LRGF',
        'SMLF',
        'EMHY',
        'IEV',
        'GSG',
        'IOO',
        'IXC',
        'IXG',
        'IXJ',
        'GHYG',
        'MXI',
        'IXN',
        'IXP',
        'HYXU',
        'GVI',
        'WPS',
        'IDV',
        'ILF',
        'EPU',
        'EWA',
        'EWO',
        'BKF',
        'EWK',
        'EWZ',
        'EWC',
        'ECH',
        'ECNS',
        'EFA',
        'EFG',
        'EFV',
        'EZU',
        'EEM',
        'EWQ',
        'EWG',
        'VEGI',
        'EWH',
        'EIRL',
        'EIS',
        'EWI',
        'EWJ',
        'SCJ',
        'EWM',
        'EWW',
        'EWN',
        'EPP',
        'EPHE',
        'EPOL',
        'ERUS',
        'EWS',
        'EZA',
        'EWY',
        'EWP',
        'EWD',
        'EWL',
        'EWT',
        'THD',
        'EWU',
        'IYLD',
        'JKL',
        'REM',
        'IGE',
        'IGM',
        'IGN',
        'IGV',
        'REZ',
        'IWB',
        'IWF',
        'IWD',
        'IWM',
        'IWO',
        'IWN',
        'IWV',
        'IWR',
        'IWS',
        'IWP',
        'OEF',
        'IVW',
        'IVE',
        'IJK',
        'IJJ',
        'IJS',
        'SLV',
        'TIP',
        'ITA',
        'IYM',
        'IAI',
        'IYK',
        'IYC',
        'IYE',
        'IYF',
        'IYG',
        'IYH',
        'IHF',
        'ITB',
        'IYJ',
        'IAK',
        'IHI',
        'IEO',
        'IEZ',
        'IHE',
        'IYR',
        'IYW',
        'IYZ',
        'IDU',
        'HYG',
        'LQD',
        'IAU']

        nasdaq_tickers =['SNCR',
        'SURG',
        'SGYPQ',
        'SNPS',
        'SYPR',
        'TROW',
        'TRSI',
        'TATT',
        'TTDKY',
        'TRTC',
        'TESS',
        'TGTX',
        'TCRD',
        'TMMI',
        'TORM',
        'TSRI',
        'TTMI',
        'TTWO',
        'TLF',
        'TEDU',
        'TAUG',
        'TAYD',
        'TECD',
        'TCCO',
        'TGEN',
        'TTEC',
        'TELL',
        'TLSYY',
        'WRLS',
        'WDRP',
        'TENX',
        'TERP',
        'TRXXF',
        'TSCDY',
        'TSLA',
        'XPER',
        'TTEK',
        'TTPH',
        'TCBI',
        'TXN',
        'ANDE',
        'TBBK',
        'BONTQ',
        'CG',
        'CAKE',
        'DSGX',
        'DXYN',
        'XONE',
        'FLIC',
        'HAIN',
        'CUBA',
        'INTG',
        'KEYW',
        'KHC',
        'MDCO',
        'MEET',
        'MIDD',
        'NDAQ',
        'NAVG',
        'PRSC',
        'TTD',
        'ULTI',
        'YORW',
        'NCTY',
        'THOR',
        'TIVO',
        'TLRY',
        'TSBK',
        'TKRFF',
        'TITN',
        'TNXP',
        'TSEM',
        'TW',
        'TWER',
        'TSCO',
        'TXCCQ',
        'TWMC',
        'TACT',
        'TRNS',
        'TGA',
        'TBIO',
        'ERBB',
        'TA',
        'TZOO',
        'TSRMF',
        'TRVN',
        'TCBK',
        'TMXN',
        'TRMB',
        'TRIB',
        'TRIP',
        'TROV',
        'TNEN',
        'TRST',
        'TRMK',
        'TUES',
        'TOUR',
        'FOX',
        'PRTS',
        'USEG',
        'GROW',
        'UEXCF',
        'UFPT',
        'UMBF',
        'UPMKY',
        'ULGX',
        'ECOL',
        'USEI',
        'DANOY',
        'USAT',
        'USAK',
        'UTSI',
        'UBNT',
        'UURAF',
        'ULTA',
        'UCTT',
        'RARE',
        'ULBI',
        'UMPQ',
        'UNAM',
        'UBSH',
        'UAHC',
        'UBCP',
        'UBSI',
        'UCBI',
        'UCFC',
        'UAL',
        'UFCS',
        'UIHC',
        'UBFO',
        'USLM',
        'UTHR',
        'UNTY',
        'DKGR',
        'OLED',
        'UEIC',
        'UFPI',
        'USAP',
        'UPWK',
        'URPTF',
        'URBF',
        'URBN',
        'UTMD',
        'VEON',
        'VWSYF',
        'VVUS',
        'VOXX',
        'VSEC',
        'VALU',
        'VNDA',
        'VNQI',
        'VXUS',
        'VREX',
        'VASO',
        'VECO',
        'UGLD',
        'ZIV',
        'VLXC',
        'VEOEY',
        'VCYT',
        'VSTM',
        'CBDD',
        'VRSN',
        'VCEL',
        'VRNT',
        'VRML',
        'VRTX',
        'VSAT',
        'VICL',
        'VICR',
        'VKIN',
        'VLGEA',
        'VIRT',
        'VRTS',
        'VTGN',
        'VOD',
        'VLTC',
        'VYGR',
        'WDFC',
        'WDDD',
        'WSFS',
        'WVFC',
        'WBA',
        'WASH',
        'WCFB',
        'WB',
        'WERN',
        'WSBC',
        'WTBA',
        'TRDX',
        'WEDXF',
        'WABC',
        'WSTL',
        'WDC',
        'WNEB',
        'WPRT',
        'WWR',
        'WEYS',
        'WEYL',
        'WHZT',
        'WSC',
        'WLFC',
        'WINMQ',
        'WINT',
        'WNBD',
        'WINS',
        'WTFC',
        'WETF',
        'WWD',
        'WDAY',
        'WRLD',
        'WHEN',
        'WNTR',
        'WMGI',
        'WYNN',
        'VISL',
        'XOMA',
        'XSNX',
        'XEL',
        'XNCR',
        'XLNX',
        'XNET',
        'YRCW',
        'YY',
        'YNDX',
        'YZCAY',
        'YARIY',
        'YTEN',
        'YGEHY',
        'YIPI',
        'DBUB',
        'ZAAP',
        'Z',
        'ZIOP',
        'ZAZA',
        'ZFGN',
        'ZLAB',
        'ZBRA',
        'ZVTK',
        'DZSI',
        'ZG',
        'ZN',
        'ZION',
        'ZIXI',
        'ZGNX',
        'ZDPY',
        'ZOOM',
        'ZTCOY',
        'ZUMZ',
        'ZNGA',
        'LIFE',
        'ADDYY',
        'BEBE',
        'SCOR',
        'EBAY',
        'EHTH',
        'PLUS',
        'IENT',
        'IQ',
        'IRBT',
        'TLT',
        'IGF',
        'ACWI',
        'AAXJ',
        'EWZS',
        'MCHI',
        'SCZ',
        'EUFN',
        'IBB',
        'AIA',
        'ICLN',
        'IJT',
        'LULU',
        'XDSL',
        'SPRT',
        'QURE']

        # uncomment below when switching
        # todo, all all norwegian stocks here automatically
        #@tickers.concat ose_tickers
        #@tickers.concat oax_tickers
        #@tickers.concat st_tickers
        # # @tickers.concat ngm_tickers # does not appear to be covered by API

        #@tickers.concat nyse_tickers
        #@tickers.concat amex_tickers
        #@tickers.concat nasdaq_tickers


        # remove duplicates
        @tickers = @tickers.uniq

        # sort alphabetically

        @tickers = @tickers.sort_by { |ticker| ticker.downcase }
        @tickers.map!(&:downcase)

        # remove duplicates
        @tickers = @tickers.uniq

        #set_stock_data(@tickers) # yahoo api no longer works # import all stocks favorited by users #TODO: also, those added to portfolios when that feature is added

        #  fetch all norwegian/swedish/US stocks from netfonds 
        import_ose_stocks()
        import_oax_stocks()
        import_st_stocks()
        import_ngm_stocks() # since this is not covered by yahoo api
        import_nyse_stocks()
        import_amex_stocks()
        import_nasdaq_stocks()

        #@tickers = ["nhy.ol", "tsla", "funcom.ol"]

        import_all_stocks_from_rapidapi(@tickers)

    end

    def import_ose_stocks ()

      # this is the way we get all Oslo stocks, direct from netfonds 15 min delayed
      # get stocks from all on one page at http://www.netfonds.no/quotes/kurs.php?exchange=OSE&sec_types=&ticks=&table=tab&sort=alphabetic

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase + ".ol"
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=OSE&sec_types=&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end

    def import_oax_stocks ()

      # this is the way we get all Oslo Access stocks, direct from netfonds 15 min delayed
      # get stocks from all on one page at http://www.netfonds.no/quotes/kurs.php?exchange=OAX&sec_types=&ticks=&table=tab&sort=alphabetic

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase + ".ol" # oax stocks are stored in yahoo as .ol, not .oax, so we need to be handle them manually and store them
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=OAX&sec_types=&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end


    def import_st_stocks ()

      # this is the way we get all Stochholm stocks, direct from netfonds 15 min delayed
      # get stocks from all on one page at http://www.netfonds.no/quotes/kurs.php?exchange=OAX&sec_types=&ticks=&table=tab&sort=alphabetic

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase + ".st"
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=ST&sec_types=&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end

    def import_ngm_stocks ()

      # this is the way we get all Stochholm nordig growth market stocks, direct from netfonds 15 min delayed
      # get stocks from all on one page at http://www.netfonds.no/quotes/kurs.php?exchange=OAX&sec_types=&ticks=&table=tab&sort=alphabetic

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase + ".st"
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=NGM&sec_types=S&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end
    
def import_nyse_stocks ()

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=N&sec_types=&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end
    
def import_amex_stocks ()

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=A&sec_types=&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end
    
def import_nasdaq_stocks ()

      def read(url)
       CSV.new(open(url), :headers => :first_row, col_sep: "\t").each do |line|

         symbol = line[1].downcase
         last = line[2].to_f
         change = line[5].to_f
         last_close = line[9].to_f
         
         percent_change = (((last - last_close)/last_close)*100).round(2).to_s + "%"
         
         if last == 0 # if no trades in stock today, last will be 0 and therefore change should be 0 also
          percent_change = 0
          last = last_close # also do this so we have a price to show
         
         end

         puts symbol + " last: " + last.to_s + " change: " + change.to_s + " yesterday: " + last_close.to_s + " change %: "  + percent_change.to_s
         ::PluginStore.set("stock_price", symbol, last.to_s)
         ::PluginStore.set("stock_change_percent", symbol, percent_change.to_s)
         #::PluginStore.set("stock_last_updated", symbol, last_updated) #todo: add
        
       end
      end

      read("http://www.netfonds.no/quotes/kurs.php?exchange=O&sec_types=&ticks=&table=tab&sort=alphabetic")

      #puts "#{symbol} / #{price} / #{change_percent}"

      puts "Done!"

    end   
    def set_stock_data (tickers)

      # handles multiple stocks in one request
        if !tickers.nil? 

          tickers = tickers.uniq
          to_be_processed = []

          # don't processs OL stocks here anymore, that has a separate Job
          tickers.each do |stock|

            if ![".ol", ".OL", ".oax", ".OAX", ".ST", ".st"].any? { |word| stock.include?(word) }
                to_be_processed.push(stock)
            end
            
          end

          tickers = to_be_processed

          puts "Fetching stock data for #{tickers.size} stocks: #{tickers}"
        
          #tickers = ["aapl", "aga.ol", "akso.ol", "amd", "apcl.ol", "asetek.ol", "avm.ol", "axa.ol", "bionor.ol", "biotec.ol", "bird.ol", "bitcoin-xbt.st", "btcusd=x", "dno.ol", "fro.ol", "funcom.ol", "gig.ol", "hugo.ol", "idex.ol", "iox.ol", "kit.ol", "nano.ol", "nas.ol", "natto.ol", "natto.st", "nel.ol", "next.ol", "nod.ol", "nom.ol", "nor.ol", "ocy.ol", "opera.ol", "ork.ol", "pho.ol", "seam.st", "sf.st", "star-a.st", "star-b.st", "tel.ol", "thin.ol", "til.ol"]

          #stocks = StockQuote::Stock.quote(tickers) #old unreliable method, but ok for historical data

          # since we only get accurate data from Yahoo when we ask for a few stocks at a time, process everything in batches

          ticker_batches = tickers.each_slice(1).to_a

          ticker_batches.each_with_index do | ticker_batch, batch_index |
              
              #sleep(1 * (1 + batch_index)) # add a 5 second delay between fetching stock data to not get blocked by yahoo


              tickers = ticker_batch.compact.join(",") #compact removes nil values

              #source = 'http://finance.yahoo.com/webservice/v1/symbols/' + tickers + '/quote?format=json&view=detail' #old way
              
              source = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20csv%20where%20url%3D'http%3A%2F%2Fdownload.finance.yahoo.com%2Fd%2Fquotes.csv%3Fs%3D" + tickers + "%26f%3Dsl1d1t1c1p2ohgvt1d1%26e%3D.csv'%20and%20columns%3D'symbol%2Cprice%2Cdate%2Ctime%2Cchange%2Cchg_percent%2Ccol1%2Chigh%2Clow%2Ccol2%2Clast_trade_time%2Clast_trade_date'&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback="
              #source = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20csv%20where%20url%3D%27http%3A%2F%2Fdownload.finance.yahoo.com%2Fd%2Fquotes.csv%3Fs%3D" + tickers + "%26f%3Dsl1d1t1c1p2ohgv%26e%3D.csv%27%20and%20columns%3D%27symbol%2Cprice%2Cdate%2Ctime%2Cchange%2Cchg_percent%2Ccol1%2Chigh%2Clow%2Ccol2%27&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback="
              puts source
              
             # conn = Faraday.new(:url => 'https://query.yahooapis.com') do |faraday|
              #  faraday.request  :url_encoded             # form-encode POST params
               # faraday.response :logger                  # log requests to STDOUT
                #faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
              #end

              #response = conn.get do |req|
              #  req.url "/v1/public/yql?q=select%20*%20from%20csv%20where%20url%3D%27http%3A%2F%2Fdownload.finance.yahoo.com%2Fd%2Fquotes.csv%3Fs%3D" + tickers + "%26f%3Dsl1d1t1c1p2ohgv%26e%3D.csv%27%20and%20columns%3D%27symbol%2Cprice%2Cdate%2Ctime%2Cchange%2Cchg_percent%2Ccol1%2Chigh%2Clow%2Ccol2%27&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback="
              ##  req.headers['User-Agent'] = '{
               #   "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36",
                #  "browser": {
              #       "name": "Chrome",
              #       "version": "53.0.2785.116",
              #       "major": "53"
              #     },
              #     "engine": {
              #       "version": "537.36",
              #       "name": "WebKit"
              #     },
              #     "os": {
              #       "name": "Mac OS",
              #       "version": "10.10.5"
              #     },
              #     "device": {},
              #     "cpu": {}
              #   }'
              # end

              resp = Net::HTTP.get_response(URI.parse(source))
              
              puts "code: "
              puts resp.code

              if resp.code == "200" # skip next steps if any error (no stock data etc)


                data = resp.body
                puts data
                #result = JSON.parse(data)
                result = JSON.parse(resp.body)

                puts result

                #stocks = result["list"]["resources"] #old way
                
                if !result["query"].nil? && !result["query"]["results"].nil? && !result["query"]["results"]["row"].nil?
                
                  stocks = result["query"]["results"]["row"]

                  puts "processing.."
                  puts result["query"]["count"]
                  puts "stocks"

                  puts stocks

                  for index in 0 ... result["query"]["count"]

                    puts "-- Processing: #{index} in batch #{batch_index}"

                    if result["query"]["count"] > 1
                      symbol = result["query"]["results"]["row"][index]["symbol"].downcase 
                    else
                      symbol = result["query"]["results"]["row"]["symbol"].downcase 
                    end

                    #symbol = result["list"]["resources"][index]["resource"]["fields"]["symbol"].downcase # old way

                    unless symbol.nil? || symbol == ""

                      symbol = symbol.downcase

                      if result["query"]["count"] > 1
                        price = result["query"]["results"]["row"][index]["price"]
                      else
                        price = result["query"]["results"]["row"]["price"]
                      end

                      if price == "N/A" 
                        price = "0" # something the numberanimator can handle
                      end

                      #last_updated = result["query"]["results"]["row"][index]["utctime"]
                      
                      if result["query"]["count"] > 1
                        change_percent = result["query"]["results"]["row"][index]["chg_percent"]
                      else
                        change_percent = result["query"]["results"]["row"]["chg_percent"]
                      end

                      puts "#{symbol} / #{price} / #{change_percent}"

                      ::PluginStore.set("stock_price", symbol, price)
                      ::PluginStore.set("stock_change_percent", symbol, change_percent)
                      #::PluginStore.set("stock_last_updated", symbol, last_updated)
                      
                    end 

                  #puts "#{stocks[index].to_json}"
                end
              end
            
            end
        

          end

          puts "Done!"

        end

    end

    def import_all_stocks_from_rapidapi(tickers)

      tickers_to_import = tickers

      # handles multiple stocks in one request
      puts "starting"
        if !tickers_to_import.nil? 
          puts "2"

          tickers_to_import = tickers_to_import.uniq
          to_be_processed = []

          puts tickers_to_import

          # don't processs OL stocks here anymore, that has a separate Job
          #tickers.each do |stock|

           # if ![".ol", ".OL", ".oax", ".OAX", ".ST", ".st"].any? { |word| stock.include?(word) }
             #   to_be_processed.push(stock)
            #end
            
          #end

          #tickers = to_be_processed

          puts "Fetching stock data for #{tickers_to_import.size} stocks: #{tickers_to_import}"
        
          #tickers = ["aapl", "aga.ol", "akso.ol", "amd", "apcl.ol", "asetek.ol", "avm.ol", "axa.ol", "bionor.ol", "biotec.ol", "bird.ol", "bitcoin-xbt.st", "btcusd=x", "dno.ol", "fro.ol", "funcom.ol", "gig.ol", "hugo.ol", "idex.ol", "iox.ol", "kit.ol", "nano.ol", "nas.ol", "natto.ol", "natto.st", "nel.ol", "next.ol", "nod.ol", "nom.ol", "nor.ol", "ocy.ol", "opera.ol", "ork.ol", "pho.ol", "seam.st", "sf.st", "star-a.st", "star-b.st", "tel.ol", "thin.ol", "til.ol"]

          #stocks = StockQuote::Stock.quote(tickers) #old unreliable method, but ok for historical data

          # since we only get accurate data from Yahoo when we ask for a few stocks at a time, process everything in batches

          ticker_batches = tickers_to_import.each_slice(80).to_a # doesn't work well after 80 at a time

          ticker_batches.each_with_index do | ticker_batch, batch_index |
              
              #sleep(1 * (1 + batch_index)) # add a 5 second delay between fetching stock data to not get blocked by yahoo

              tickers = ticker_batch.compact.join(",") #compact removes nil values
              puts tickers
              source = "https://apidojo-yahoo-finance-v1.p.rapidapi.com/market/get-quotes?region=US&lang=en&symbols=" + tickers

              uri = URI.parse(source)
              http = Net::HTTP.new(uri.host, uri.port)
               #= "Authorization: key=34750c705518e0927e0e16f87f65ee60";
              http.use_ssl = true
              http.verify_mode = OpenSSL::SSL::VERIFY_NONE
              request_header = { "X-RapidAPI-Host" => "apidojo-yahoo-finance-v1.p.rapidapi.com", "X-RapidAPI-Key" => "ee6e3e1f1dmshe3286ace2bfae9ap12f657jsn9c02a0696281" }
              request = Net::HTTP::Get.new(uri.request_uri, request_header)
              #request.add_field("Authorization", "Authorization: 34750c705518e0927e0e16f87f65ee60")
              result = http.request(request)

              #puts response
              #puts result.body

                #stocks = result["list"]["resources"] #old way

                result = JSON.parse(result.body)
                
                if !result.nil? && !result["quoteResponse"].nil? && !result["quoteResponse"]["result"].nil?
                
                  stocks = result["quoteResponse"]["result"]

                  puts "processing.."
                  puts stocks.count                  
                  puts "stocks"

                  #puts stocks

                  stocks.each_with_index do |stock, index|

                    puts "-- Processing: #{index} in batch #{batch_index}"
                    #puts stock
                    #puts stock["symbol"]

                    #if result["quoteResponse"]["count"] > 1
                     # symbol = result["query"]["results"]["row"][index]["symbol"].downcase 
                    #else
                     # symbol = result["query"]["results"]["row"]["symbol"].downcase 
                    #end

                    symbol = stock["symbol"].downcase

                    #symbol = result["list"]["resources"][index]["resource"]["fields"]["symbol"].downcase # old way

                    unless symbol.nil? || symbol == "" || stock["regularMarketPrice"].nil? || stock["regularMarketPrice"] == "" || stock["regularMarketChangePercent"].nil? || stock["regularMarketChangePercent"] == ""

                      symbol = symbol.downcase

                      price = stock["regularMarketPrice"]
                      last_updated = stock["regularMarketTime"]
                     
                      if price == "N/A" 
                        price = "0" # something the numberanimator can handle
                      end

                      #last_updated = result["query"]["results"]["row"][index]["utctime"]
                      
                      change_percent = stock["regularMarketChangePercent"].round(2).to_s + "%"
#                      change_percent = (change_percent.to_f * 100) + "%"
                      
                      puts "#{symbol} / #{price} / #{change_percent}"

                      ::PluginStore.set("stock_price", symbol, price)
                      ::PluginStore.set("stock_change_percent", symbol, change_percent)
                      ::PluginStore.set("stock_last_updated", symbol, last_updated)
                      
                    end 

                  #puts "#{stocks[index].to_json}"
                end
              end
            
           # end
        
          end

          puts "Done!"

        end

    end

  end
end
